### ISSUE TITLE
sort and show cuisines

### ISSUE THREAD

**Issue by ToriRae324** [ejohn156/ExpectationByDestination#11]
*User Story*
As a user, I want to be able to find a restaurant by cuisine type

*Acceptance Criteria*
- [x] Cuisines button has multiple options
- [x] a place to display cuisine results
- [x] cuisine values match api
- [x] api search retrieves results by cuisine

**Comment by ToriRae324** [comment]
Cuisine dropdown has 10 options, button values match api requirements

**Comment by ejohn156** [comment]
I will work on js to make on click functions of those buttons into searches!
